name: reusable-secret-test
on:
  workflow_call:
    secrets:
      MY_SECRET:
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secrets context keys
        run: echo '${{ toJSON(secrets) }}'
